"""Convert Desktop's upstream item artwork into monochrome Flipper icon assets."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

from PIL import Image


ALIASES = {
    "RC Car 2 (duck)": "rc_car_2_duck_sprite.png",
    "Building Block": "bldg_block_sprite.png",
    "! ! (Clone)": "!_!_sprite.png",
    "Cone (animation)": "cone_sprite.png",
    "Flower (animation)": "flower_sprite.png",
    "Poop (animation)": "poop_sprite.png",
    "Cake (animation)": "cake_sprite.png",
    "Heart (animation)": "heart_sprite.png",
    "Snake (animation)": "snake_sprite.png",
}


def sprite_filename(name: str) -> str:
    return ALIASES.get(name, name.lower().replace(" ", "_") + "_sprite.png")


def convert(source: Path, destination: Path) -> None:
    with Image.open(source) as original:
        rgba = original.convert("RGBA")
    if rgba.width > 28 or rgba.height > 28:
        rgba.thumbnail((28, 28), Image.Resampling.NEAREST)
    background = Image.new("RGBA", rgba.size, "white")
    background.alpha_composite(rgba)
    monochrome = background.convert("L").point(lambda value: 255 if value > 210 else 0, "1")
    canvas = Image.new("1", (30, 30), 1)
    canvas.paste(monochrome, ((30 - rgba.width) // 2, (30 - rgba.height) // 2))
    canvas.save(destination, format="PNG", optimize=True)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--desktop-root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--mapping", type=Path, required=True)
    args = parser.parse_args()
    desktop = args.desktop_root.resolve()
    sys.path.insert(0, str(desktop))
    from tamagometer_core import GIFT_ITEMS

    source_dir = desktop / "assets" / "item-sprites"
    args.output.mkdir(parents=True, exist_ok=True)
    generated: list[int] = []
    for item_id, name in GIFT_ITEMS:
        source = source_dir / sprite_filename(name)
        if not source.exists():
            continue
        convert(source, args.output / f"item_{item_id:03d}.png")
        generated.append(item_id)
    lines = [
        "/* Generated by tools/convert_item_sprites.py. */",
        '#include "tamagometer_item_icons.h"',
        '#include "tamagometer_enhanced_icons.h"',
        "#include <stddef.h>",
        "",
        "static const Icon* const connection_icons[181] = {",
        *(f"    [{item_id}] = &I_item_{item_id:03d}," for item_id in generated),
        "};",
        "",
        "const Icon* tamagometer_item_icon(uint8_t item_id) {",
        "    return item_id < 181 ? connection_icons[item_id] : NULL;",
        "}",
        "",
    ]
    args.mapping.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {len(generated)} of {len(GIFT_ITEMS)} Connection icons")


if __name__ == "__main__":
    main()
